ChrisTrent_ITrellis/Models/Todo.cs
using System;
using System.Activities.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChrisTrent_ITrellis.Models
{
    public class Todo
    {
        [Key]
        [Required]
        [Display(Name = "ID")]
        public int ID  { get; set; }
        
        [Required]
        [Display(Name = "To Do")]
        public string toDo_Item { get; set; }

        [Required]
        [Display(Name = "Deadline Date")]
        public DateTime deadLineDate { get; set; }
        [Required]
        [Display(Name = "Task Completed")]
        public bool isComplete { get; set; }

        [Display(Name = "More Details")]
        public string moreDetails { get; set; }
    }
}

ChrisTrent_ITrellis/Controllers/TodoController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ChrisTrent_ITrellis.Models;
using System;

namespace ChrisTrent_ITrellis.Controllers
{
    public class TodoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.TodoList.ToList());
        }

        public ActionResult Details(int id)
        {
            if (id == 0) //check to make sure we have a valid ID (note autoincrement when created, should never be 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.TodoList.Find(id); 
            if (todo == null) //check to see if we have returned a valid todo from database.
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        //default view for making a new todo.
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID, toDo_Item, deadLineDate, isComplete, moreDetails")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                db.TodoList.Add(todo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todo);
        }

        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.TodoList.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID, toDo_Item, deadLineDate, isComplete, moreDetails")] Todo todo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(todo).State = EntityState.Modified; //set state to modified otherwise system will reject updating with Entity framework. 
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todo);
        }

        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Todo todo = db.TodoList.Find(id);
            if (todo == null)
            {
                return HttpNotFound();
            }
            return View(todo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Todo todo = db.TodoList.Find(id);
            db.TodoList.Remove(todo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public bool isPassedDeadline(DateTime deadline)
        {
            return (deadline > DateTime.Now) ? true : false;     
        }
    }
}

ChrisTrent_ITrellis/Views/Todo/Create.cshtml
@model ChrisTrent_ITrellis.Models.Todo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Todo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.toDo_Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.toDo_Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.toDo_Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deadLineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deadLineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deadLineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isComplete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isComplete)
                    @Html.ValidationMessageFor(model => model.isComplete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.moreDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.moreDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.moreDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisTrent_ITrellis/Views/Todo/Delete.cshtml
@model ChrisTrent_ITrellis.Models.Todo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.toDo_Item)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.toDo_Item)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadLineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadLineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isComplete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moreDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moreDetails)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Todo", "Index")
        </div>
    }
</div>

ChrisTrent_ITrellis/Views/Todo/Details.cshtml
@model ChrisTrent_ITrellis.Models.Todo

@{
    ViewBag.Title = "Details";
}

<h2>Todo Details</h2>

<div>
    <h4>Todo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.toDo_Item)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.toDo_Item)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadLineDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadLineDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isComplete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.moreDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.moreDetails)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit Todo", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to Todo", "Index")
</p>

ChrisTrent_ITrellis/Views/Todo/Edit.cshtml
@model ChrisTrent_ITrellis.Models.Todo

<h2>Edit Todo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Todo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.toDo_Item, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.toDo_Item, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.toDo_Item, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deadLineDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deadLineDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deadLineDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isComplete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isComplete)
                    @Html.ValidationMessageFor(model => model.isComplete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.moreDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.moreDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.moreDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Todo", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChrisTrent_ITrellis/Views/Todo/Index.cshtml
@model IEnumerable<ChrisTrent_ITrellis.Models.Todo>

<h2>Todo Home</h2>
<br />
<div class="jumbotron">
    <div class="btn-container-index">
        <div class="row">
            @Html.ActionLink(" New Todo", "Create", "Todo", null, new { @class = "glyphicon glyphicon-plus btn btn-success" })
        </div>
    </div>
    <br />

    <table class="table table-bordered table-hover">
        <tr>
            <th>
                To Do Item:
            </th>
            <th>
                @Html.DisplayNameFor(model => model.deadLineDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isComplete)
            </th>
            <th>
                Options
            </th>
        </tr>

        @foreach (var todo in Model)
        {
            if (todo.deadLineDate < DateTime.Now && !todo.isComplete)
            {
            <tr bgcolor="#eaea65">
                <td>
                    @Html.DisplayFor(modelItem => todo.toDo_Item)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => todo.deadLineDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => todo.isComplete)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = todo.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = todo.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = todo.ID })
                </td>
            </tr>
            }
            else
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => todo.toDo_Item)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => todo.deadLineDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => todo.isComplete)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = todo.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = todo.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = todo.ID })
                    </td>
                </tr>

            }
        }
    </table>
</div>